/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projector;

import java.awt.AWTEvent;
import java.awt.Font;

/**
 *
 * @author 15096134
 */
public class ProjectionFrame extends javax.swing.JFrame implements ProjectionWindow {

    /**
     * Creates new form ProjectionFrame
     */
    public ProjectionFrame() {
        initComponents();
        getContentPane().setBackground(getBackground());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(640, 480));
        setUndecorated(true);
        setSize(new java.awt.Dimension(640, 480));

        textLabel.setFont(new java.awt.Font("SansSerif", 0, 98)); // NOI18N
        textLabel.setForeground(java.awt.Color.white);
        textLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void setText(String string) {
        textLabel.setText("<html><p></p></html>");
        String ht = "<html><p>" + string + "</p></html>";
        
        java.awt.EventQueue.invokeLater(new Runnable(){
            @Override
            public void run() {
                textLabel.setText(ht);
            }
        });

    }
    
    @Override
    public Font getFont() {
        return textLabel.getFont();
    }
    
    public void setFont(Font font) {
        textLabel.setFont(font);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel textLabel;
    // End of variables declaration//GEN-END:variables

}
