/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projector;

import java.awt.Font;

/**
 *
 * @author 15096134
 */
public class ProjectionFrame extends javax.swing.JFrame implements ProjectionWindow {

    /**
     * Creates new form ProjectionFrame
     */
    public ProjectionFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textLabel = new projector.CenterLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(640, 480));
        setUndecorated(true);
        setSize(new java.awt.Dimension(640, 480));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        textLabel.setForeground(java.awt.Color.black);
        textLabel.setFont(new java.awt.Font("SansSerif", 0, 120)); // NOI18N
        textLabel.setMinimumSize(new java.awt.Dimension(640, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        getContentPane().setBackground(getBackground());
        textLabel.checkDefaultFontSize();
    }//GEN-LAST:event_formWindowOpened

    @Override
    public void setText(String string) {
        textLabel.setText(string);
    }
    
    @Override
    public Font getFont() {
        return textLabel.getFont();
    }
    
    @Override
    public void setFont(Font font) {
        textLabel.setFont(font);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private projector.CenterLabel textLabel;
    // End of variables declaration//GEN-END:variables

}
